let toto = [
  { column: 0, id: 0, indexType: null, row: 0 },
  { column: 1, id: 1, indexType: null, row: 0 },
  { column: 2, id: 2, indexType: null, row: 0 },
  { column: 3, id: 3, indexType: null, row: 0 },
  { column: 4, id: 4, indexType: null, row: 0 },
  { column: 5, id: 5, indexType: null, row: 0 },
  { column: 1, id: 9, indexType: null, row: 1 },
  { column: 2, id: 10, indexType: null, row: 1 },
  { column: 3, id: 11, indexType: null, row: 1 },
  { column: 4, id: 12, indexType: null, row: 1 },
  { column: 5, id: 13, indexType: null, row: 1 },
  { column: 3, id: 19, indexType: null, row: 2 },
  { column: 4, id: 20, indexType: null, row: 2 },
  { column: 3, id: 27, indexType: null, row: 3 },
  { column: 4, id: 28, indexType: null, row: 3 },
  { column: 3, id: 35, indexType: null, row: 4 },
  { column: 4, id: 36, indexType: null, row: 4 },
  { column: 3, id: 43, indexType: null, row: 5 },
];
